### ISSUE TITLE
AWSSQS source's spec doesn't have the same shape with other sources

### ISSUE THREAD

**Issue by aliok** [knative-sandbox/eventing-awssqs#7]
**Describe the bug**
For example, GithubSource:
```
spec:
  ...
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1alpha1
      kind: InMemoryChannel
      name: githubchannel
```

awssqssource:
```
spec:
  ...
  sink:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: awssqs-test
```

No `ref` in AWSSQS.

Obviously, defining the `sink` with a nested `ref` ends up in reconciliation errors:

```
"level":"info","ts":"2020-09-27T01:31:32.632Z","logger":"awssqs-controller.knative.dev-eventing-contrib-awssqs-pkg-reconciler.Reconciler","caller":"controller/controller.go:513","msg":"Reconcile failed. Time taken: 316.362µs","knative.dev/traceid":"e6a8f827-651d-4f79-b832-f6697f9bdcbd","knative.dev/key":"markito/awssqssource"}
{"level":"info","ts":"2020-09-27T01:31:32.633Z","logger":"awssqs-controller.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"AwsSqsSource\", Namespace:\"markito\", Name:\"awssqssource\", UID:\"59e46f4c-d4eb-49a6-9d63-17ce8708a3e0\", APIVersion:\"sources.knative.dev/v1alpha1\", ResourceVersion:\"394679187\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' failed to track &ObjectReference{Kind:,Namespace:markito,Name:,UID:,APIVersion:,ResourceVersion:,FieldPath:,}: invalid Reference:\nAPIVersion: name part must be non-empty\nAPIVersion: name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')\nKind: a valid C identifier must start with alphabetic character or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name',  or 'MY_NAME',  or 'MyName', regex used for validation is '[A-Za-z_][A-Za-z0-9_]*')\nmust provide either Name or Selector"}
```

 **Expected behavior**
AWSSQSSource to use the same shape as other shapes.

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**

I see this comment, which is probably related:
https://github.com/knative-sandbox/eventing-awssqs/blob/master/pkg/apis/sources/v1alpha1/aws_sqs_types.go#L64
